###################################
# !!!! Do Not Edit This File !!!! #
#  Modifications are done in the  # 
#  $HOME/.zsh/zshrc.d/ directory  #
###################################

for FN in $HOME/.zsh/zshrc.d/*.sh ; do
  source "$FN"
done
