#!/bin/bash

function print_header() {
  echo "##############################"
  echo $1
  echo "##############################"
}

cd "$HOME"

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  print_header "Setting up for OS X"
  
  if [ -f "$HOME/.Brewfile" ]; then
    print_header "Setting up some dependencies for weechat / wee-slack"
    /usr/local/bin/pip install websocket-client
    mkdir -p $HOME/.weechat/python/autoload
    cd $HOME/.weechat/python
    curl -O https://raw.githubusercontent.com/wee-slack/wee-slack/master/wee_slack.py
    ln -s $HOME/.weechat/python/wee_slack.py $HOME/.weechat/python/autoload
    
    print_header "Installing utilities via brew"
    brew tap Homebrew/bundle
    brew bundle --global
  fi

  print_header "installing fonts to $HOME/Library/Fonts"
  cp -vf $HOME/.yadm/fonts/*.ttf $HOME/Library/Fonts

  print_header "Setting up faster OS X key repeat"
  defaults write -g InitialKeyRepeat -int 15 # normal minimum is 15 (225 ms)
  defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

  print_header "Redirecting iterm2's config file to local copy"
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.config/iterm2"
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
fi

if [ "$system_type" = "Linux" ]; then
  linux_type=$(uname -r)

  print_header "Installing utilities via apt-get"
  
  if [ -f "$HOME/.Debfile" ]; then 
    cat ~/.Debfile | xargs sudo apt-get install -y
  fi

  print_header "Installing fonts"

  if [[ $linux_type == *"microsoft"* ]]; then 
    echo "You will need to install fonts on your own and configure in the terminal for WSL / Windows."
  fi

fi

