#!/bin/bash

# TODO: Determine system type (OS X / Linux)
# TODO: Install basic utilities (htop, build utilities, etc)
# TODO: Execute brewfile if exists

function print_header() {
  echo "##############################"
  echo $1
  echo "##############################"
}

cd "$HOME"

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  print_header "Setting up for OS X"
  
  if [ -f "$HOME/.Brewfile" ]; then
    print_header "Installing utilities via brew"
    brew tap Homebrew/bundle
    brew bundle --global
  fi

  print_header "installing fonts to $HOME/Library/Fonts"
  cp -vf $HOME/.yadm/fonts/*.ttf $HOME/Library/Fonts

  print_header "Setting up faster OS X key repeat"
  defaults write -g InitialKeyRepeat -int 15 # normal minimum is 15 (225 ms)
  defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

  print_header "Redirecting iterm2's config file to local copy"
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.config/iterm2"
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

fi

